### ISSUE TITLE
Few ideas on your module

### ISSUE THREAD

**Issue by Astrotech89** [sparkcity/fvtt-me5e#1]
Hey there sparkcity,

Really happy to see you have done this.  I'd love to help contribute to this to add on some extra features.  

First off, ME5e only uses credits so we could probably do away with the platinum, gold, etc in exchange for just credits.

I've been trying to make this experience as idiot proof as possible for my friends so I also cataloged spells in a google spreadsheet that I'd be happy to put into a database.  Here's a link  [Spell List](https://docs.google.com/spreadsheets/d/19ntV2srO58czhNhRcAIN2YyD_GVTxPau4LCSXXYj66o/edit?usp=sharing) 

I could also put together a class progression db too.  That one will be a bit harder but I'd be happy to help work on adding some features here.

**Comment by Astrotech89** [comment]
I do see now some of the features that I had missed so I'll retract the spell list, but it does have a TRUE/FALSE for different classes.  But I did notice that the class features are missing.  I'll be happy to make a pass at creating a list of class features as well

**Comment by sparkcity** [comment]
Hey Astro!

All items (grenades, weapon mods, armor mods, and weapons) should be in the Item Catalogue and there should (unless something has gone wrong) also be spells, vehicles, feats, and the basic classes. I'm not really sure what you mean by the TRUE/FALSE in reference to the classes. But if you want to work on making a compendium of the individual class features, go for it.

Keep in mind that all entries need to be edited so they don't mention anything remotely copyright infringing. For instance, words like biotics are fine because they could be in reference to many different things. Similarly, omni-tools are fine as I've run them through the copyright database and the term isn't copyrighted. However, any and all racial names apart from human should be avoided. Same thing with organization names, anything else that would stand out as referencing existing IPs. But thank you for the help! Compendium building is tedious, so I've been doing it in chunks for my own sake, so it'll be nice to have a hand.

Next on my list is the bestiary, then my plan is to revisit to make a monsters features compendium for easier homebrewing. I'm trying out a few things to get the currencies into credits without the sheet having obvious blank spaces, I just wanted to get everything working before I inevitably broke something in the process.

**Comment by Astrotech89** [comment]
Hey Spark,

Ah good to know.  Guess I'm mostly eager to help, but it sounds like you got it.  I love the Mass Effect universe and I love DnD.  But I definitely forgot about copyrights.  I think though that the class features would be necessary update too.  

But yeah if you need a second party to help out, please reach out!
