### ISSUE TITLE
Vehicle Handling still undefined

### ISSUE THREAD

**Issue by Astrotech89** [sparkcity/fvtt-me5e#15]
Saw a while back that you had fixed this in an update, however on Forge and installed software, VH still says undefined and doesn't have proficiency button.

Tried deleting the character and rebuilding but still there

**Comment by sparkcity** [comment]
![Screenshot (73)](https://user-images.githubusercontent.com/23155686/94994171-f5487600-0563-11eb-8627-c3b15ec7a6c3.png)

So, this change is intentional due to the limitations of extending Actor5e data from the dnd5e system. The proficiency button has been removed as it breaks everything else at the moment. Until I am able to find a solution for this issue to restore functionality like the rest of the skills, there is an input box there for manual tracking of what the modifier should be. There's no automation for Vehicle Handling and that input box will initially say undefined but, once you enter text in there, it'll save that information.

This is less than ideal, I know, but this is the temporary solution until I figure out something better.
