### ISSUE TITLE
credits fields

### ISSUE THREAD

**Issue by saethone** [sparkcity/fvtt-me5e#22]
![image](https://user-images.githubusercontent.com/13894683/99062715-058f4000-2569-11eb-8762-f16e23992516.png)

credits currently has several fields which could be combined into a single field (perhaps using only the copper field which could enable compatibility with modules that distribute loot automatically)

**Comment by Astrotech89** [comment]
I forget why, but these credit slots were left on purpose.  It's a minor thing and I just use the front most field for my party's credits

**Comment by sparkcity** [comment]
Yes, currently credits has several fields because it's, frankly, a pita to mess with the 5e sheet. It populates that part of the character sheet programmatically. As 5e has 5 currencies (cp through pp), it populates 5 fields. Removing the labels is far easier than trying to remove each input field which have no simple selectors to grab onto.

I am testing out a few approaches that may or may not work.

**Comment by sparkcity** [comment]
Completed in 2.0.0.
